/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 28 05:19:08 GMT 2021
 */

package codigos;

import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class Identifier_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("U:8^3_");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("caP");
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("G2,I");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("9");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("_rsi>0vU");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador((String) null);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        boolean boolean0 = Identifier.validaIdentificador("");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        Identifier identifier0 = new Identifier();
    }
}
