/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 28 05:19:57 GMT 2021
 */

package codigos;

import org.junit.Test;

public class LadoInvalidoException_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        LadoInvalidoException ladoInvalidoException0 = new LadoInvalidoException("F^/:Y~");
    }
}
