/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 28 05:19:30 GMT 2021
 */

package codigos;

import org.junit.Ignore;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;


public class Pedido_ESTest {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "", 384.4917F);
        assertEquals(5.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "", 476.0F);
        assertEquals(10.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(true, "IYnLg(h[gIrTf7I\"S!'", 500.0F);
        assertEquals(15.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        Pedido pedido0 = new Pedido();
        // Undeclared exception!
        try {
            pedido0.calculaTaxaDesconto(false, (String) null, (-1524.1F));
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Ignore
    @Test(timeout = 4000)
    public void test04() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "bronze", (-1568.0F));
        assertEquals(0.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "codigos.Pedido", 200.0F);
        assertEquals(5.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "uL", 400.0F);
        assertEquals(10.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(true, "lI45}=}fo`tr6f~Q.Z", 0.0F);
        assertEquals(10.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "prata", (-688.2F));
        assertEquals(10.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(true, "ouro", 221.112F);
        assertEquals(15.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "?9zC\"R<6qi-J", 0.0F);
        assertEquals(0.0F, float0, 0.01F);
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        Pedido pedido0 = new Pedido();
        float float0 = pedido0.calculaTaxaDesconto(false, "", 3405.0F);
        assertEquals(15.0F, float0, 0.01F);
    }
}
